const data = [
 {
   title: "The Great Gatsby",
   author: "F. Scott Fitzgerald",
   image_url: "https://th.bing.com/th/id/OIP.P1hfBfyKdnmO2R82Ow3lewHaLH?rs=1&pid=ImgDetMain",
   price: 10.99,
   book_type: "Fiction",
 },
 {
   title: "A Brief History of Time",
   author: "Stephen Hawking",
   image_url: "https://th.bing.com/th/id/OIP.P1hfBfyKdnmO2R82Ow3lewHaLH?rs=1&pid=ImgDetMain",
   price: 15.99,
   book_type: "Science",
 },
 {
   title: "To Kill a Mockingbird",
   author: "Harper Lee",
   image_url: "https://th.bing.com/th/id/OIP.P1hfBfyKdnmO2R82Ow3lewHaLH?rs=1&pid=ImgDetMain",
   price: 12.99,
   book_type: "Fiction",
 },
 {
   title: "The Art of War",
   author: "Sun Tzu",
   image_url: "https://th.bing.com/th/id/OIP.P1hfBfyKdnmO2R82Ow3lewHaLH?rs=1&pid=ImgDetMain",
   price: 8.5,
   book_type: "Philosophy",
 },
 {
   title: "Clean Code",
   author: "Robert C. Martin",
   image_url: "https://th.bing.com/th/id/OIP.P1hfBfyKdnmO2R82Ow3lewHaLH?rs=1&pid=ImgDetMain",
   price: 24.99,
   book_type: "Programming",
 },
 {
   title: "Sapiens: A Brief History of Humankind",
   author: "Yuval Noah Harari",
   image_url: "https://th.bing.com/th/id/OIP.P1hfBfyKdnmO2R82Ow3lewHaLH?rs=1&pid=ImgDetMain",
   price: 19.99,
   book_type: "History",
 },
 {
   title: "1984",
   author: "George Orwell",
   image_url: "https://th.bing.com/th/id/OIP.P1hfBfyKdnmO2R82Ow3lewHaLH?rs=1&pid=ImgDetMain",
   price: 9.99,
   book_type: "Dystopian",
 },
 {
   title: "The Alchemist",
   author: "Paulo Coelho",
   image_url: "https://th.bing.com/th/id/OIP.P1hfBfyKdnmO2R82Ow3lewHaLH?rs=1&pid=ImgDetMain",
   price: 14.99,
   book_type: "Fiction",
 },
 {
   title: "Cracking the Coding Interview",
   author: "Gayle Laakmann McDowell",
   image_url: "https://th.bing.com/th/id/OIP.P1hfBfyKdnmO2R82Ow3lewHaLH?rs=1&pid=ImgDetMain",
   price: 29.99,
   book_type: "Programming",
 },
 {
   title: "Meditations",
   author: "Marcus Aurelius",
   image_url: "https://th.bing.com/th/id/OIP.P1hfBfyKdnmO2R82Ow3lewHaLH?rs=1&pid=ImgDetMain",
   price: 11.5,
   book_type: "Philosophy",
 },
];
module.exports=data;